### PR TITLE
Add description param to database endpoint

### PR DESCRIPTION
**Pull request by FlorianWilhelm**
According to the official Notion API there is a new parameter 'description' in the database endpoint for [update](https://developers.notion.com/reference/update-a-database).

### CODE REVIEW

**Comment by ramnes** [comment]
Danke Florian! CI is broken but it's mostly unrelated to your PR, so I'll fix this and merge.

**Comment by FlorianWilhelm** [comment]
Thanks @ramnes!

**Comment by FlorianWilhelm** [comment]
Thanks @ramnes!

**Comment by FlorianWilhelm** [comment]
Hi @ramnes, are you planning on having a minor release to include the update of descriptions? I think it would be pretty nice to have a release with it :-) Thanks.

**Comment by ramnes** [comment]
@FlorianWilhelm I just released 2.1.0! Thanks for the nudge. :)

**Pull request merged**
