### PR TITLE
added test to ensure that key-value pairs with value of None get removed

### PR DESCRIPTION
**Pull request by nicobako**
@ramnes , I forgot to add a test to ensure that this new `pick` functionality is tested.

P.S. I am having a hard time setting up my _pre-commit_ to get all of the tests to pass. Was wondering if you could give me more details on how to do that. Thanks.

### CODE REVIEW

**Comment by ramnes** [comment]
Looking good, thanks!

What problem do you get with pre-commit exactly?

**Comment by nicobako** [comment]
Actually, I got the _pre-commit_ to work... I'm using _wsl_ on Windows and just had to install gcc.

I don't know the `NOTION_TOKEN` environment variable used in the tests... not sure if that's something you want to share with others though.

**Comment by ramnes** [comment]
You don't need one as long as you're using the cassettes (records of the API results that are saved in `tests/cassettes/`), which should be the default if you've installed `requirements/dev.txt`.

`NOTION_TOKEN` is only useful when you want to record a new cassette or regenerate previous ones. And any default Notion workspace should work IIRC!

**Comment by ramnes** [comment]
I just added a commit that should help, is it better now? :)

**Comment by nicobako** [comment]
> I just added a commit that should help, is it better now? :)

Awesome! Everything passes! Thanks!

**Pull request merged**
