### PR TITLE
Issue #61 - Handled Timeout Errors

### PR DESCRIPTION
**Pull request by mutt0-ds**
As discussed in the issue #61, since response.raise_for_status() is never raising a TimeoutException, I created a function for checking if the status code belongs in the "Timeout" category.

I'm curious to hear your feedbacks, I hope that my approach makes sense :)

### CODE REVIEW

**Comment by ramnes** [comment]
Hey @mutt0-ds, thanks for the work!

The implementation looks wrong to me; isn't httpx raising an exception when there's a timeout? If so, we need to catch it when doing the request, not trying to look at the HTTP code, that we'll only get if we actually get an answer from the remote machine.

**Comment by mutt0-ds** [comment]
Hey @ramnes thank you for your reply! 
You are right, I need to handle the timeout not in the raise_for_status() function, but first, in when it's sending the request!
So I handled the TimeoutException in request(), since the TimeoutExpection is raised there.  
Let me know if this time I understood correctly!

**Comment by ramnes** [comment]
Yeah, that's it! The asynchronous client also needs it though.

**Comment by mutt0-ds** [comment]
Updater for the AsyncClient too :)

**Comment by ramnes** [comment]
Great, thanks!

**Pull request merged**
